apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: apphub-dashboards
    
build:
  tagPolicy:
    envTemplate:
      template: 5m

  artifacts:
    - image: ttl.sh/dash-app
      docker:
        dockerfile: Dockerfile
      context: dash
  
    - image: ttl.sh/streamlit-app
      docker:
        dockerfile: Dockerfile
      context: streamlit

    - image: ttl.sh/reflex-app
      docker:
        dockerfile: Dockerfile
      context: reflex/app

    - image: ttl.sh/nicegui-app
      docker:
        dockerfile: Dockerfile
      context: nicegui  

    - image: ttl.sh/taipy-app
      docker:
        dockerfile: Dockerfile
      context: taipy

    - image: ttl.sh/panel-app
      docker:
        dockerfile: Dockerfile
      context: panel
      
    - image: ttl.sh/solara-app
      docker:
        dockerfile: Dockerfile
      context: solara
      
deploy:
  helm:
    releases:
      - name: apphub-dashboards
        remoteChart: eoepca-plus/application-hub
        namespace: jupyter
        version: 1.0.19
        createNamespace: true
        valuesFiles: 
        - values.yaml
        setFiles:
          configYml: ./files/hub/config.yml
          jupyterConfig: ./files/hub/jupyterhub_config.py
        setValues:
              jupyterhub.hub.image.pullSecrets: []
              jupyterhub.hub.db.pvc.storageClassName: standard
              jupyterhub.hub.extraEnv.STORAGE_CLASS: standard
              jupyterhub.proxy.secretToken: "032d5bfe141a7eab86d57587879b33c5d168617cacb339823d7f47fe2933f880"
              jupyterhub.hub.extraEnv.APP_HUB_NAMESPACE: jupyter
              jupyterhub.hub.networkPolicy.enabled: false
           
    hooks:
          before:
            - host:
                command: ["sh", "-c", "config/generate-config.sh"]
                os: [darwin, linux]
manifests:
  rawYaml:
  - sk-k8s/cluster-role-binding.yaml
  - sk-k8s/script.yaml
  - sk-k8s/job.yaml

portForward:
- resourceType: service
  resourceName: application-hub-proxy-public
  namespace: jupyter 
  port: 80
  localPort: 8080