profiles:
- config_maps: []
  default_url: null
  definition:
    default: false
    description: This profile is used to demonstrate a Panel dashboard (https://panel.holoviz.org/)
    display_name: Panel
    kubespawner_override:
      cpu_guarantee: 1
      cpu_limit: 2
      extra_resource_guarantees: {}
      extra_resource_limits: {}
      image: ttl.sh/panel-app:14cfb5f5c9f1dbbbded8196ee0adf95c3be0a25c38b834016ae9bfb3c0092fab
      mem_guarantee: 1G
      mem_limit: 2G
    slug: profile_panel
  env_from_config_maps: []
  env_from_secrets: []
  groups:
  - group-a
  - group-b
  id: profile_dash
  image_pull_secrets: []
  init_containers: []
  manifests: []
  node_selector: {}
  pod_env_vars:
    HOME: /workspace
  role_bindings: null
  secret_mounts: []
  volumes:
  - access_modes:
    - ReadWriteOnce
    claim_name: workspace-claim
    name: workspace-volume
    persist: true
    size: 10Gi
    storage_class: standard
    volume_mount:
      mount_path: /workspace
      name: workspace-volume
- config_maps: []
  default_url: null
  definition:
    default: false
    description: This profile is used to demonstrate a Streamlit dashboard (https://streamlit.io/)
    display_name: Streamlit
    kubespawner_override:
      cpu_guarantee: 1
      cpu_limit: 2
      extra_resource_guarantees: {}
      extra_resource_limits: {}
      image: ttl.sh/streamlit-app:f9f0a122d7eaf9224c7ee44902d5207415706f42ef5565ab81db994b76eb6117
      mem_guarantee: 1G
      mem_limit: 2G
    slug: profile_streamlit
  env_from_config_maps: []
  env_from_secrets: []
  groups:
  - group-a
  - group-b
  id: profile_dash
  image_pull_secrets: []
  init_containers: []
  manifests: []
  node_selector: {}
  pod_env_vars:
    HOME: /workspace
  role_bindings: null
  secret_mounts: []
  volumes:
  - access_modes:
    - ReadWriteOnce
    claim_name: workspace-claim
    name: workspace-volume
    persist: true
    size: 10Gi
    storage_class: standard
    volume_mount:
      mount_path: /workspace
      name: workspace-volume
- config_maps: []
  default_url: null
  definition:
    default: false
    description: This profile is used to demonstrate a Taipy dashboard (https://taipy.io/)
    display_name: Taipy
    kubespawner_override:
      cpu_guarantee: 1
      cpu_limit: 2
      extra_resource_guarantees: {}
      extra_resource_limits: {}
      image: ttl.sh/taipy-app:4f22931f31b6ca9b0a932a54c5b872ef3fccde2db4bedb92435873d5448c42a6
      mem_guarantee: 1G
      mem_limit: 2G
    slug: profile_taipy
  env_from_config_maps: []
  env_from_secrets: []
  groups:
  - group-a
  - group-b
  id: profile_dash
  image_pull_secrets: []
  init_containers: []
  manifests: []
  node_selector: {}
  pod_env_vars:
    HOME: /workspace
  role_bindings: null
  secret_mounts: []
  volumes:
  - access_modes:
    - ReadWriteOnce
    claim_name: workspace-claim
    name: workspace-volume
    persist: true
    size: 10Gi
    storage_class: standard
    volume_mount:
      mount_path: /workspace
      name: workspace-volume
- config_maps: []
  default_url: null
  definition:
    default: false
    description: This profile is used to demonstrate a Solara dashboard (https://solara.dev/)
    display_name: Solara
    kubespawner_override:
      cpu_guarantee: 1
      cpu_limit: 2
      extra_resource_guarantees: {}
      extra_resource_limits: {}
      image: ttl.sh/solara-app:084d192820c834bcb946928c3768a6d245179b92f6d1dd95650adb6d774be244
      mem_guarantee: 1G
      mem_limit: 2G
    slug: profile_solara
  env_from_config_maps: []
  env_from_secrets: []
  groups:
  - group-a
  - group-b
  id: profile_dash
  image_pull_secrets: []
  init_containers: []
  manifests: []
  node_selector: {}
  pod_env_vars:
    HOME: /workspace
  role_bindings: null
  secret_mounts: []
  volumes:
  - access_modes:
    - ReadWriteOnce
    claim_name: workspace-claim
    name: workspace-volume
    persist: true
    size: 10Gi
    storage_class: standard
    volume_mount:
      mount_path: /workspace
      name: workspace-volume
