name: build
on:
  push:
    branches:
    - develop
    - main

    paths:
    # Only rebuild website when apps have changed
    - 'streamlit/**'
    - 'reflex/**'
    - 'nicegui/**'
    - 'dash/**'
    - .github/**
    - docs/**
    - codemeta.json
jobs:

  version:
    #needs: validate

    runs-on: ubuntu-latest

    outputs:
      app-version: ${{ steps.set-version.outputs.version }}

    steps:
    - uses: actions/checkout@v2
    - run: echo "APP_VERSION=$(cat codemeta.json | jq -r .version )" >> $GITHUB_ENV
    - run: echo app version is $APP_VERSION
    - id: set-version
      run: echo "::set-output name=version::$APP_VERSION"

  container-build:

    needs: version

    runs-on: ubuntu-latest

    strategy:
      matrix:
        step: [streamlit, panel, solara, taipy]

    steps:
    - uses: actions/checkout@v2
    - run: echo version ${{needs.version.outputs.app-version}}
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: build & push image
      run: |
        IMAGE_ID=ghcr.io/eoepca/apphub-dashboards/${{ matrix.step }}
        docker build ${{ matrix.step }} --file ${{ matrix.step }}/Dockerfile --tag ${{ matrix.step }}
        docker tag ${{ matrix.step }} $IMAGE_ID:${{needs.version.outputs.app-version}}
        docker push $IMAGE_ID:${{needs.version.outputs.app-version}}

  